[psql]
  dbname = "paychain"
  host = "localhost"
  port = 5432
  user = "postgres"
  pass = "postgres"
  sslmode = "disable"
  schema = "public"
  blacklist = ["schema_migrations"]

[auto-columns]
  created = "created_at"
  updated = "updated_at"

[null-types]
  timestamp = "null.Time"

[types]
  "kyc_status_enum" = "string"
  "user_role_enum" = "string"
  "merchant_type_enum" = "string"
  "merchant_status_enum" = "string"
